<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="16070" started-at="2021-09-02T06:10:25Z" finished-at="2021-09-02T06:10:41Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="16070" started-at="2021-09-02T06:10:25Z" finished-at="2021-09-02T06:10:41Z">
      <class name="com.test.seleniumTest.SeleniumTest">
        <test-method status="PASS" signature="testSetup()[pri:0, instance:com.test.seleniumTest.SeleniumTest@147ed70f]" name="testSetup" is-config="true" duration-ms="8861" started-at="2021-09-01T23:10:25Z" finished-at="2021-09-01T23:10:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetup -->
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.test.seleniumTest.SeleniumTest@147ed70f]" name="openBrowser" is-config="true" duration-ms="3241" started-at="2021-09-01T23:10:34Z" finished-at="2021-09-01T23:10:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="PASS" signature="signUp()[pri:0, instance:com.test.seleniumTest.SeleniumTest@147ed70f]" name="signUp" duration-ms="1185" started-at="2021-09-01T23:10:38Z" description="This method validates the sign up functionality" finished-at="2021-09-01T23:10:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method status="PASS" signature="postSignUp()[pri:0, instance:com.test.seleniumTest.SeleniumTest@147ed70f]" name="postSignUp" is-config="true" duration-ms="104" started-at="2021-09-01T23:10:39Z" finished-at="2021-09-01T23:10:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postSignUp -->
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.test.seleniumTest.SeleniumTest@147ed70f]" name="openBrowser" is-config="true" duration-ms="2441" started-at="2021-09-01T23:10:39Z" finished-at="2021-09-01T23:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:com.test.seleniumTest.SeleniumTest@147ed70f]" name="test2" duration-ms="3" started-at="2021-09-01T23:10:41Z" finished-at="2021-09-01T23:10:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[numbers don't add up expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: numbers don't add up expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at com.test.seleniumTest.SeleniumTest.test2(SeleniumTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="postSignUp()[pri:0, instance:com.test.seleniumTest.SeleniumTest@147ed70f]" name="postSignUp" is-config="true" duration-ms="11" started-at="2021-09-01T23:10:41Z" finished-at="2021-09-01T23:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postSignUp -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.test.seleniumTest.SeleniumTest@147ed70f]" name="afterClass" is-config="true" duration-ms="210" started-at="2021-09-01T23:10:41Z" finished-at="2021-09-01T23:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.test.seleniumTest.SeleniumTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
